language: c
sudo: required
group: edge
dist: trusty
services:
  - docker
env:
  global:
    - IMAGE="$DOCKER_USER/ruby-openssl-docker"
before_install:
  - sudo apt-get -qq update
  # https://github.com/travis-ci/travis-ci/issues/4596
  - echo "${TRAVIS_COMMIT_RANGE} -> ${TRAVIS_COMMIT_RANGE/.../..}"
  - TRAVIS_COMMIT_RANGE="${TRAVIS_COMMIT_RANGE/.../..}"
  - |
    if [ "${DOCKER_USER}" != "" -a "${DOCKER_PASSWORD}" != "" ]; then
      files=$(git diff --name-only "${TRAVIS_COMMIT_RANGE}") || true
      for file in ${files}; do
        if [[ "${file}" =~ ^(tool/ruby-openssl-docker/|Dockerfile) ]]; then
          BUILD_RUBY_OPENSSL_DOCKER=true
          break
        fi
      done
    fi
  - echo "DOCKER_USER=${DOCKER_USER=} BUILD_RUBY_OPENSSL_DOCKER=${BUILD_RUBY_OPENSSL_DOCKER=}"
install:
  - sudo sh -c "curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
  - sudo chmod +x /usr/local/bin/docker-compose
script:
  - docker -v
  - docker-compose -v
  - |
    if [ "${BUILD_RUBY_OPENSSL_DOCKER}" = true ]; then
      docker pull $IMAGE:pr && \
        sed -i "/^FROM/ s/zzak/${DOCKER_USER}/" Dockerfile && \
        sed -i '/^FROM/ s/testing/pr/' Dockerfile && \
        grep ^FROM Dockerfile
    fi
  - docker-compose build --no-cache
  - docker-compose run test
stages:
  - prepare
  - test
  - deploy
matrix:
  fast_finish: true
  include:
    - name: push ruby-openssl-docker image for testing
      stage: deploy
      # if: (env(DOCKER_USER) IS present) AND (env(DOCKER_PASSWORD) IS present) AND (type = push) AND (branch = master)
      if: (env(DOCKER_USER) IS present) AND (env(DOCKER_PASSWORD) IS present) AND (type = push)
      script:
        - |
          if [ "${BUILD_RUBY_OPENSSL_DOCKER}" = true ]; then
            docker pull $IMAGE:pr && \
              echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin && \
              docker tag $IMAGE:pr $IMAGE:testing && \
              docker push $IMAGE:testing
          fi
  allow_failures:
    - language: ruby
      rvm: ruby-head
    - env: RUBY_VERSION=ruby-2.5 OPENSSL_VERSION=openssl-1.1.1
